### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement mediapipe

### ISSUE THREAD

**Issue by Ryo-Kawanami** [Kazuhito00/mediapipe-python-sample#2]
I tried to install mediapipe using pip3
`pip3 install mediapipe`

but I got this error
`ERROR: Could not find a version that satisfies the requirement mediapipe`

Anyone can install mediapipe using pip or pip3?

**Comment by Kazuhito00** [comment]
I think it can be installed regardless of pip or pip3.

I have never experienced that error, but an acquaintance ran into a similar error.
The error occurred because MediaPipe only supports Python 3.6-3.8.
Therefore, he used the following command to avoid the error:
`py -3.8 -m pip install mediapipe`

**Comment by Ryo-Kawanami** [comment]
In my case, it doesn't work...

In addition, I checked pip version, then confirmed that requirements you said.

```
pip3 --version
pip 20.3.3 from /Users/ryokawanami/.pyenv/versions/3.7.9/envs/mediapipe3.7.9/lib/python3.7/site-packages/pip (python 3.7)
```

I used Mac OS Mojave 10.14.6

**Comment by Kazuhito00** [comment]
I think the Python and pip versions are fine.
If so, is it possible to install directly by specifying whl with the following command?
`pip install https://files.pythonhosted.org/packages/b3/0a/7d068c64d5ce1124e4dd5ecfaf5bb6cdcffcf7a631f63a2b704e63d544b0/mediapipe-0.8.2-cp37-cp37m-macosx_10_15_x86_64.whl`

**Comment by Kazuhito00** [comment]
It will close because time has passed.
If you have another problem, please create the issue again.
