### ISSUE TITLE
Multi Person?

### ISSUE THREAD

**Issue by HoiBunCa** [Kazuhito00/mediapipe-python-sample#3]
How to track many people, do you have any idea?
Thank you!!

**Comment by Kazuhito00** [comment]
At this time, MediaPipe Pose and Holistics do not have a multi-person detection option.
I think it's easy to extract a human area using EfficientDet or SSD, etc and input the extracted area into MediaPipe.

**Comment by Kazuhito00** [comment]
It will close because time has passed.
If you have another problem, please create the issue again.
