### ISSUE TITLE
Getting this error on Facemesh.py

### ISSUE THREAD

**Issue by hasankhurshid29** [Kazuhito00/mediapipe-python-sample#5]
TypeError: __init__() got an unexpected keyword argument 'refine_landmarks'

**Comment by hasankhurshid29** [comment]
Traceback (most recent call last):
  File "sample_facemesh.py", line 346, in <module>
    main()
  File "sample_facemesh.py", line 64, in main
    min_tracking_confidence=min_tracking_confidence,
TypeError: __init__() got an unexpected keyword argument 'refine_landmarks'

**Comment by Kazuhito00** [comment]
What version of MediaPipe are you using?
'refine_landmarks' option is valid from v0.8.8.
If you want to use an older version of MediaPipe, switch to a tag that matches your version.

**Comment by hasankhurshid29** [comment]
> What version of MediaPipe are you using? 'refine_landmarks' option is valid from v0.8.8. If you want to use an older version of MediaPipe, switch to a tag that matches your version.

I am following this tutorial: https://github.com/PINTO0309/mediapipe-bin
How can upgrade mediapipe version without messing up anything

**Comment by Kazuhito00** [comment]
This repository does not support the upgrade method of MediaPipe version.
